spring.application.name=cloudvandana-salesforce-crud

server.port=8080

salesforce.client-id=${SALESFORCE_CLIENT_ID}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}

salesforce.redirect-uri=http://localhost:8080/oauth2/callback

salesforce.authorization-url=https://login.salesforce.com/services/oauth2/authorize

salesforce.token-url=https://login.salesforce.com/services/oauth2/token